[workspace]
resolver = "2"
members = ["spz", "spz-lib"]

[workspace.dependencies]
tokio = "1.47.0"

[profile.release]
lto = true

[profile.release.package.spz]
codegen-units = 1
opt-level = 3
debug = true
