[target.'cfg(all(target_os = "windows", target_arch = "x86_64"))']
rustflags = [
    "-C", "target-cpu=x86-64-v3"
]

[target.'cfg(all(target_os = "linux", target_arch = "x86_64"))']
rustflags = [
    "-C", "target-cpu=x86-64-v3"
]

[target.'cfg(all(target_os = "linux", target_arch = "aarch64"))']
rustflags = [
    "-C", "target-feature=+aes,+dotprod,+fp16,+rcpc,+lse,+neon,+sve"
]

[target.'cfg(all(target_os = "macos", target_arch = "aarch64"))']
rustflags = [
    "-C", "target-cpu=apple-m1"
]
